name: mda

channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - fastparquet
  - jupyter
  - ipykernel

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - torchaudio==2.7.1+cu128
      - tqdm
      - tensorboard
      - koreanize-matplotlib